USE [master]
GO
/****** Object:  Database [TeacherDB]    Script Date: 9/28/2025 3:47:30 PM ******/
CREATE DATABASE [TeacherDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TeacherDB', FILENAME = N'F:\New folder\MSSQL16.MSSQLSERVER\MSSQL\DATA\TeacherDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TeacherDB_log', FILENAME = N'F:\New folder\MSSQL16.MSSQLSERVER\MSSQL\DATA\TeacherDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TeacherDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TeacherDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TeacherDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TeacherDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TeacherDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TeacherDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TeacherDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TeacherDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TeacherDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TeacherDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TeacherDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TeacherDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TeacherDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TeacherDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TeacherDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TeacherDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TeacherDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TeacherDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TeacherDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TeacherDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TeacherDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TeacherDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TeacherDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TeacherDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TeacherDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TeacherDB] SET  MULTI_USER 
GO
ALTER DATABASE [TeacherDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TeacherDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TeacherDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TeacherDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TeacherDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TeacherDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TeacherDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TeacherDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO
USE [TeacherDB]
GO
/****** Object:  Table [dbo].[Tbl_Teacher]    Script Date: 9/28/2025 3:47:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Teacher](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Phone] [varchar](50) NULL,
	[Subject] [varchar](50) NULL,
	[DeleteFlag] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tbl_Teacher] ADD  CONSTRAINT [DF_Tbl_Teacher_DeleteFlag]  DEFAULT ((0)) FOR [DeleteFlag]
GO
USE [master]
GO
ALTER DATABASE [TeacherDB] SET  READ_WRITE 
GO
